### ISSUE TITLE
Some reference

### ISSUE THREAD

**Issue by ricardobarroslourenco** [UBC-MOAD/docs#11]
Hi! 

I was reading this docs page ( https://github.com/UBC-MOAD/docs/blob/main//jupyter.rst ), where you show how to load a Jupyter session interactively.

I wonder if you are using Dask in such sessions, and how is the experience? When I open a session and use a `SLURMCluster` setup, I can get some scalability, but often I get queued due to lack of priority. 

Thanks

**Comment by douglatornell** [comment]
Hi @ricardobarroslourenco !

Nobody in our group has tried to use dask in Jupyter on the ComputeCanada clusters, so we haven't hit the issue you are experiencing. Generally, we work out the flow of what we want to do with dask in Jupyter on local machines where we don't have to worry about priority, then convert the code to a Python module that we can run as a batch job on the clusters. That avoids the issue of trying to get an interactive session with enough resources to do significant things with dask.

There were a couple of SharcNet webinars a while ago about using dask on the clusters:
* https://www.youtube.com/watch?v=FwhtHOKU8Jk
* https://www.youtube.com/watch?v=GEdhmCjBBbQ

I don't recall all of the content of those, but they might contain some clues that would help you move forward.
